version: 2
jobs:
  lint:
    docker:
       - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Install requirements
          command: sudo pip install -r requirements.txt
      - run:
          name: Run pylint
          command: pylint src



workflows:
  version: 2
  build:
    jobs:
      - lint