version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            sudo apt-get install -y python-pip virtualenv
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade setuptools wheel


      - run:
          name: Create package
          command: python setup.py sdist bdist_wheel

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          
      - run:
          name: Push package
          command: |
            curl -F package=@$(ls -t dist/ecs_cluster-*-py2-none-any.whl) https://$GEMFURY_TOKEN@push.fury.io/silvercar/

workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
